version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=user
      - POSTGRES_DB=DJUNG
    networks:
      - my_network

  djung-be:
    container_name: djung_be
    build: .
    volumes:
      - ./assets:/usr/src/app/dist/assets
      - ./logs:/usr/src/app/log
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
